let nome = prompt("Qual é o seu nome?")
alert(`Seu nome é ${nome}`)
let p = prompt("Quantas horas você trabalha por dia?")
let t = prompt("Quanto você recebe por dia?")
alert(`Voce recebe ${t/p} por hora`)